services:
    alazjj_simple_bootstrap.form.type.datepicker:
        class: Alazjj\SimpleBootstrapBundle\Form\Type\DatepickerType
        arguments:
            - "%locale%"
        tags:
            - { name: form.type, alias: datepicker }

    alazjj_simple_bootstrap.form.type.colorpicker:
        class: Alazjj\SimpleBootstrapBundle\Form\Extension\Type\ColorpickerType
        tags:
            - { name: form.type, alias: colorpicker }

    alazjj_simple_bootstrap.form.type.typeahead:
        class: Alazjj\SimpleBootstrapBundle\Form\Extension\Type\TypeaheadType
        tags:
            - { name: form.type, alias: typeahead }

    alazjj_simple_bootstrap.form.extension:
        class: Alazjj\SimpleBootstrapBundle\Form\Extension\Type\FormTypeExtension
        tags:
            - { name: form.type_extension, alias: form }

    alazjj_simple_bootstrap.choice.extension:
        class: Alazjj\SimpleBootstrapBundle\Form\Extension\Type\ChoiceTypeExtension
        tags:
            - { name: form.type_extension, alias: choice }

    alazjj_simple_bootstrap.date.extension:
        class: Alazjj\SimpleBootstrapBundle\Form\Extension\Type\DateTypeExtension
        arguments:
            - "%locale%"
        tags:
            - { name: form.type_extension, alias: date }